'use client'
import {useEffect,useState} from 'react'
import {jsPDF} from 'jspdf'
import {supabase} from '../../../lib/supabase'

export default function QuoteDetail({params}){
 const [quote,setQuote]=useState(null),[items,setItems]=useState([]),[company,setCompany]=useState(null),[loading,setLoading]=useState(true),[msg,setMsg]=useState(''),[pdfing,setPdfing]=useState(false),[sharing,setSharing]=useState(false)
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login';return}const {data:q}=await supabase.from('quotes').select('*, clients(name,document_number,phone,email,address)').eq('id',params.id).maybeSingle();if(!q){location.href='/historial';return}const {data:i}=await supabase.from('quote_items').select('*').eq('quote_id',q.id).order('created_at');const {data:m}=await supabase.from('company_members').select('company_id').eq('user_id',user.id).limit(1).maybeSingle();const {data:c}=await supabase.from('companies').select('*').eq('id',m?.company_id).maybeSingle();setQuote(q);setItems(i||[]);setCompany(c);setLoading(false)})()},[params.id])
 const makePdfBlob=()=>{const doc=new jsPDF();let y=20;doc.setFontSize(20);doc.setFont('helvetica','bold');doc.text(company?.business_name||'Mi negocio',20,y);doc.setFontSize(11);doc.setFont('helvetica','normal');y+=8;[company?.legal_name,company?.address,company?.phone,company?.email].filter(Boolean).forEach(t=>{doc.text(String(t),20,y);y+=6});y+=5;doc.setFontSize(16);doc.setFont('helvetica','bold');doc.text(`COTIZACIÓN ${quote.quote_number}`,20,y);y+=7;doc.setFontSize(10);doc.setFont('helvetica','normal');doc.text(`Fecha: ${quote.issue_date}`,20,y);y+=8;doc.setFont('helvetica','bold');doc.text('Cliente',20,y);doc.setFont('helvetica','normal');y+=6;doc.text(quote.clients?.name||'Consumidor final',20,y);y+=10;doc.setFont('helvetica','bold');doc.text('Descripción',20,y);doc.text('Cant.',125,y);doc.text('Precio',145,y);doc.text('Total',175,y);y+=5;doc.line(20,y,190,y);y+=7;doc.setFont('helvetica','normal');items.forEach(i=>{if(y>270){doc.addPage();y=20}doc.text(String(i.description||'').slice(0,48),20,y);doc.text(String(i.quantity),125,y);doc.text(`S/ ${Number(i.unit_price).toFixed(2)}`,145,y);doc.text(`S/ ${Number(i.line_total).toFixed(2)}`,175,y);y+=7});y+=5;doc.line(120,y,190,y);y+=8;doc.text(`Subtotal: S/ ${Number(quote.subtotal).toFixed(2)}`,145,y);y+=7;doc.text(`IGV: S/ ${Number(quote.igv).toFixed(2)}`,145,y);y+=8;doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text(`TOTAL: S/ ${Number(quote.total).toFixed(2)}`,145,y);if(quote.notes){y+=12;doc.setFontSize(10);doc.text('Notas:',20,y);y+=6;doc.setFont('helvetica','normal');doc.text(doc.splitTextToSize(String(quote.notes),170),20,y)}return doc}
 const pdf=()=>{if(!quote)return;setPdfing(true);try{makePdfBlob().save(`${quote.quote_number}.pdf`)}catch(e){setMsg('No se pudo generar el PDF.')}setPdfing(false)}
 const whatsapp=async()=>{if(!quote)return;setMsg('');setSharing(true);try{const phone=(quote.clients?.phone||'').replace(/\D/g,'');const text=`Hola${quote.clients?.name?' '+quote.clients.name:''}, te envío la cotización ${quote.quote_number} por S/ ${Number(quote.total).toFixed(2)}.`;const doc=makePdfBlob();const blob=doc.output('blob');const file=new File([blob],`${quote.quote_number}.pdf`,{type:'application/pdf'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:`Cotización ${quote.quote_number}`,text,files:[file]});return}if(phone)window.open(`https://wa.me/${phone}?text=${encodeURIComponent(text+' Te adjunto el PDF de la cotización.')}`,'_blank');else setMsg('No se pudo compartir el PDF directamente. Descárgalo y envíalo por WhatsApp.')}catch(e){if(e?.name!=='AbortError')setMsg('La función de compartir no está disponible en este dispositivo. Puedes descargar el PDF y enviarlo por WhatsApp.')}finally{setSharing(false)}}
 const print=()=>window.print()
 if(loading)return <main className="shell"><section className="main"><div className="card">Cargando cotización…</div></section></main>
 return <main className="shell"><header className="topbar no-print"><a className="brand" href="/dashboard">Cotiza<span>Ya</span></a><a href="/historial">← Historial</a></header><section className="main"><div className="hero no-print"><div><p className="eyebrow">COTIZACIÓN</p><h1>{quote.quote_number}</h1><p className="muted">{quote.issue_date} · {quote.clients?.name||'Sin cliente / Consumidor final'}</p></div><div className="row"><button className="btn secondary" onClick={whatsapp} disabled={sharing}>{sharing?'Preparando…':'Compartir PDF'}</button><button className="btn secondary" onClick={pdf} disabled={pdfing}>{pdfing?'Generando…':'Descargar PDF'}</button><button className="btn" onClick={print}>Imprimir</button></div></div>{msg&&<div className="notice no-print">{msg}</div>}<article className="card quote-paper"><div className="quote-head"><div><h2>{company?.business_name||'Mi negocio'}</h2><p className="muted">{company?.legal_name||''}</p><p>{company?.address||''}</p><p>{company?.phone||''} {company?.email?'· '+company.email:''}</p></div><div className="quote-meta"><strong>{quote.quote_number}</strong><br/>Fecha: {quote.issue_date}</div></div><hr/><div><h3>Cliente</h3><p><b>{quote.clients?.name||'Consumidor final'}</b></p>{quote.clients?.document_number&&<p>DNI/RUC: {quote.clients.document_number}</p>}{quote.clients?.address&&<p>{quote.clients.address}</p>}</div><table className="quote-table"><thead><tr><th>Descripción</th><th>Cant.</th><th>Precio</th><th>Total</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.description}</td><td>{i.quantity}</td><td>S/ {Number(i.unit_price).toFixed(2)}</td><td>S/ {Number(i.line_total).toFixed(2)}</td></tr>)}</tbody></table><div className="quote-totals"><div>Subtotal <b>S/ {Number(quote.subtotal).toFixed(2)}</b></div><div>IGV <b>S/ {Number(quote.igv).toFixed(2)}</b></div><div className="total">Total <b>S/ {Number(quote.total).toFixed(2)}</b></div></div>{quote.notes&&<div className="quote-notes"><h3>Notas</h3><p>{quote.notes}</p></div>}</article></section></main>
}