'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../../lib/supabase'

export default function QuoteDetail({params}){
 const [quote,setQuote]=useState(null),[items,setItems]=useState([]),[company,setCompany]=useState(null),[loading,setLoading]=useState(true),[msg,setMsg]=useState('')
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login';return}const {data:q}=await supabase.from('quotes').select('*, clients(name,document_number,phone,email,address)').eq('id',params.id).maybeSingle();if(!q){location.href='/historial';return}const {data:i}=await supabase.from('quote_items').select('*').eq('quote_id',q.id).order('created_at');const {data:m}=await supabase.from('company_members').select('company_id').eq('user_id',user.id).limit(1).maybeSingle();const {data:c}=await supabase.from('companies').select('*').eq('id',m?.company_id).maybeSingle();setQuote(q);setItems(i||[]);setCompany(c);setLoading(false)})()},[params.id])
 const whatsapp=()=>{const phone=(quote.clients?.phone||'').replace(/\D/g,'');const text=`Hola${quote.clients?.name?' '+quote.clients.name:''}, te envío la cotización ${quote.quote_number} por S/ ${Number(quote.total).toFixed(2)}.`;if(!phone)return setMsg('Este cliente no tiene teléfono registrado.');window.open(`https://wa.me/${phone}?text=${encodeURIComponent(text)}`,'_blank')}
 const print=()=>window.print()
 if(loading)return <main className="shell"><section className="main"><div className="card">Cargando cotización…</div></section></main>
 return <main className="shell"><header className="topbar no-print"><a className="brand" href="/dashboard">Cotiza<span>Ya</span></a><a href="/historial">← Historial</a></header><section className="main"><div className="hero no-print"><div><p className="eyebrow">COTIZACIÓN</p><h1>{quote.quote_number}</h1><p className="muted">{quote.issue_date} · {quote.clients?.name||'Sin cliente / Consumidor final'}</p></div><div className="row"><button className="btn secondary" onClick={whatsapp}>WhatsApp</button><button className="btn" onClick={print}>Imprimir / PDF</button></div></div>{msg&&<div className="notice no-print">{msg}</div>}<article className="card quote-paper"><div className="quote-head"><div><h2>{company?.business_name||'Mi negocio'}</h2><p className="muted">{company?.legal_name||''}</p><p>{company?.address||''}</p><p>{company?.phone||''} {company?.email?'· '+company.email:''}</p></div><div className="quote-meta"><strong>{quote.quote_number}</strong><br/>Fecha: {quote.issue_date}</div></div><hr/><div><h3>Cliente</h3><p><b>{quote.clients?.name||'Consumidor final'}</b></p>{quote.clients?.document_number&&<p>DNI/RUC: {quote.clients.document_number}</p>}{quote.clients?.address&&<p>{quote.clients.address}</p>}</div><table className="quote-table"><thead><tr><th>Descripción</th><th>Cant.</th><th>Precio</th><th>Total</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.description}</td><td>{i.quantity}</td><td>S/ {Number(i.unit_price).toFixed(2)}</td><td>S/ {Number(i.line_total).toFixed(2)}</td></tr>)}</tbody></table><div className="quote-totals"><div>Subtotal <b>S/ {Number(quote.subtotal).toFixed(2)}</b></div><div>IGV <b>S/ {Number(quote.igv).toFixed(2)}</b></div><div className="total">Total <b>S/ {Number(quote.total).toFixed(2)}</b></div></div>{quote.notes&&<div className="quote-notes"><h3>Notas</h3><p>{quote.notes}</p></div>}</article></section></main>
}