'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase'

export default function Cotizacion(){
 const [company,setCompany]=useState(null),[clients,setClients]=useState([]),[products,setProducts]=useState([]),[clientId,setClientId]=useState(''),[items,setItems]=useState([]),[notes,setNotes]=useState(''),[msg,setMsg]=useState(''),[saving,setSaving]=useState(false)
 const [selected,setSelected]=useState('')
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login';return}const {data:m}=await supabase.from('company_members').select('company_id').eq('user_id',user.id).limit(1).maybeSingle();if(!m){setMsg('No encontramos tu negocio.');return}const [{data:c},{data:cl},{data:p}]=await Promise.all([supabase.from('companies').select('*').eq('id',m.company_id).maybeSingle(),supabase.from('clients').select('*').eq('company_id',m.company_id).order('name'),supabase.from('products').select('*').eq('company_id',m.company_id).order('name')]);setCompany(c);setClients(cl||[]);setProducts(p||[]);const params=new URLSearchParams(location.search);setClientId(params.get('client')||'')})()},[])
 const addItem=()=>{const p=products.find(x=>x.id===selected);if(!p)return;setItems([...items,{product_id:p.id,description:p.name,quantity:1,unit_price:Number(p.price||0)}]);setSelected('')}
 const update=(i,k,v)=>setItems(items.map((x,n)=>n===i?{...x,[k]:k==='quantity'||k==='unit_price'?Number(v):v}:x))
 const subtotal=useMemo(()=>items.reduce((s,x)=>s+(Number(x.quantity)||0)*(Number(x.unit_price)||0),0),[items]);const igv=useMemo(()=>subtotal*Number(company?.igv??18)/100,[subtotal,company]);const total=subtotal+igv
 const save=async e=>{e.preventDefault();setMsg('');if(!items.length)return setMsg('Agrega al menos un producto o servicio.');setSaving(true);const {data:{user}}=await supabase.auth.getUser();const {data:m}=await supabase.from('company_members').select('company_id').eq('user_id',user.id).limit(1).maybeSingle();const {data:q,error}=await supabase.from('quotes').insert({company_id:m.company_id,client_id:clientId||null,quote_number:'COT-'+Date.now().toString().slice(-8),status:'draft',issue_date:new Date().toISOString().slice(0,10),subtotal,igv,total,notes}).select().single();if(error){setSaving(false);return setMsg(error.message)}const {error:itemError}=await supabase.from('quote_items').insert(items.map(x=>({...x,quote_id:q.id,line_total:(Number(x.quantity)||0)*(Number(x.unit_price)||0)})));setSaving(false);if(itemError)return setMsg(itemError.message);setMsg('Cotización guardada correctamente.');setItems([]);setNotes('')}
 return <main className="shell"><header className="topbar"><a className="brand" href="/dashboard">Cotiza<span>Ya</span></a><a href="/dashboard">Inicio</a></header><section className="main"><div className="hero"><div><p className="eyebrow">NUEVA COTIZACIÓN</p><h1>Cotizar</h1><p className="muted">Puedes cotizar con cliente o sin cliente.</p></div></div><form onSubmit={save}><div className="card"><h3>Cliente</h3><select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Sin cliente / Consumidor final</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="card" style={{marginTop:16}}><h3>Productos y servicios</h3><div className="row"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecciona un producto o servicio</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} — S/ {Number(p.price).toFixed(2)}</option>)}</select><button type="button" className="btn" onClick={addItem}>Agregar</button></div>{items.length===0?<p className="muted">Todavía no has agregado partidas.</p>:items.map((x,i)=><div className="line" key={i}><div style={{flex:1}}><b>{x.description}</b><div className="row"><input type="number" min="0.01" step="0.01" value={x.quantity} onChange={e=>update(i,'quantity',e.target.value)} style={{width:90}}/><span>×</span><input type="number" min="0" step="0.01" value={x.unit_price} onChange={e=>update(i,'unit_price',e.target.value)} style={{width:120}}/></div></div><b>S/ {(x.quantity*x.unit_price).toFixed(2)}</b></div>)}</div><div className="card" style={{marginTop:16}}><h3>Notas</h3><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Condiciones, forma de pago, observaciones…" style={{width:'100%',minHeight:90,padding:12,border:'1px solid #ccd3df',borderRadius:10}}/><div className="line"><span>Subtotal</span><b>S/ {subtotal.toFixed(2)}</b></div><div className="line"><span>IGV ({Number(company?.igv??18).toFixed(0)}%)</span><b>S/ {igv.toFixed(2)}</b></div><div className="total"><span>Total</span><span style={{float:'right'}}>S/ {total.toFixed(2)}</span></div>{msg&&<div className="notice" style={{marginTop:15}}>{msg}</div>}<button className="btn" disabled={saving} style={{marginTop:18}}>{saving?'Guardando…':'Guardar cotización'}</button></div></form></section></main>
}