'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'

export default function Clientes(){
 const [clients,setClients]=useState([]),[form,setForm]=useState({name:'',document_number:'',phone:'',email:'',address:''}),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login';return}const {data:m}=await supabase.from('company_members').select('company_id').eq('user_id',user.id).limit(1).maybeSingle();if(!m){setMsg('No encontramos tu negocio.');setLoading(false);return}const {data,error}=await supabase.from('clients').select('*').eq('company_id',m.company_id).order('name');if(error)setMsg(error.message);setClients(data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const save=async e=>{e.preventDefault();setSaving(true);setMsg('');const {data:{user}}=await supabase.auth.getUser();const {data:m}=await supabase.from('company_members').select('company_id').eq('user_id',user.id).limit(1).maybeSingle();if(!m){setSaving(false);return setMsg('No encontramos tu negocio.')}const {error}=await supabase.from('clients').insert({...form,company_id:m.company_id});if(error)setMsg(error.message);else{setForm({name:'',document_number:'',phone:'',email:'',address:''});await load()}setSaving(false)}
 const remove=async id=>{if(!confirm('¿Eliminar este cliente?'))return;const {error}=await supabase.from('clients').delete().eq('id',id);if(error)setMsg(error.message);else load()}
 if(loading)return <main className="shell"><section className="main"><div className="card">Cargando clientes…</div></section></main>
 return <main className="shell"><header className="topbar"><a className="brand" href="/dashboard">Cotiza<span>Ya</span></a><a href="/dashboard">Inicio</a></header><section className="main"><div className="hero"><div><p className="eyebrow">CLIENTES</p><h1>Clientes</h1><p className="muted">Administra tus clientes y abre su expediente.</p></div></div>{msg&&<div className="notice">{msg}</div>}<div className="grid two"><form className="card" onSubmit={save}><h2>Nuevo cliente</h2><div className="field"><label>Nombre / Razón social</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>DNI / RUC</label><input value={form.document_number} onChange={e=>setForm({...form,document_number:e.target.value})}/></div><div className="field"><label>Teléfono</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="field"><label>Correo</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="field"><label>Dirección</label><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div><button className="btn" disabled={saving}>{saving?'Guardando…':'Guardar cliente'}</button></form><div><h2>Mis clientes</h2>{clients.length===0?<div className="card"><p className="muted">Todavía no tienes clientes registrados.</p></div>:clients.map(c=><div className="card" key={c.id} style={{marginBottom:12}}><div className="row"><div style={{flex:1}}><h3>{c.name}</h3><p className="muted">{c.document_number||'Sin documento'} · {c.phone||'Sin teléfono'}</p></div><a className="btn secondary small" href={'/clientes/'+c.id}>Expediente</a></div><div className="actions"><a className="btn small" href={'/cotizacion?client='+c.id}>+ Cotizar</a><button className="btn danger small" onClick={()=>remove(c.id)}>Eliminar</button></div></div>)}</div></div></section></main>
}