'use client'
import {useState} from 'react'
import {supabase} from '../../lib/supabase'

export default function Registro(){
 const [form,setForm]=useState({full_name:'',business_name:'',email:'',password:'',confirm:''})
 const [msg,setMsg]=useState(''); const [loading,setLoading]=useState(false)
 const submit=async(e)=>{e.preventDefault();setMsg('');if(form.password.length<8)return setMsg('La contraseña debe tener al menos 8 caracteres.');if(form.password!==form.confirm)return setMsg('Las contraseñas no coinciden.');setLoading(true);const {error}=await supabase.auth.signUp({email:form.email,password:form.password,options:{data:{full_name:form.full_name,business_name:form.business_name},emailRedirectTo:window.location.origin+'/auth/callback'}});setLoading(false);setMsg(error?error.message:'Cuenta creada. Revisa tu correo para confirmar tu cuenta antes de iniciar sesión.')}
 const change=(k,v)=>setForm({...form,[k]:v})
 return <main className="shell"><header className="topbar"><a className="brand" href="/">Cotiza<span>Ya</span></a></header><section className="main"><form className="form" onSubmit={submit}><h1>Crear cuenta</h1><p className="muted">Empieza a crear cotizaciones profesionales.</p>{msg&&<div className="notice">{msg}</div>}<div className="field"><label>Nombre completo</label><input required value={form.full_name} onChange={e=>change('full_name',e.target.value)} placeholder="Tu nombre"/></div><div className="field"><label>Nombre del negocio</label><input required value={form.business_name} onChange={e=>change('business_name',e.target.value)} placeholder="Mi negocio"/></div><div className="field"><label>Correo electrónico</label><input required type="email" value={form.email} onChange={e=>change('email',e.target.value)} placeholder="correo@ejemplo.com"/></div><div className="field"><label>Contraseña</label><input required minLength="8" type="password" value={form.password} onChange={e=>change('password',e.target.value)} placeholder="Mínimo 8 caracteres"/></div><div className="field"><label>Confirmar contraseña</label><input required type="password" value={form.confirm} onChange={e=>change('confirm',e.target.value)} placeholder="Repite tu contraseña"/></div><button className="btn" disabled={loading}>{loading?'Creando…':'Crear cuenta'}</button><p className="muted">¿Ya tienes cuenta? <a href="/login">Inicia sesión</a></p></form></section></main>
}