'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'

export default function Configuracion(){
 const [company,setCompany]=useState(null),[form,setForm]=useState({business_name:'',legal_name:'',tax_id:'',address:'',phone:'',email:'',currency:'PEN',igv:18}),[logo,setLogo]=useState(''),[file,setFile]=useState(null),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login';return}const {data:m}=await supabase.from('company_members').select('company_id').eq('user_id',user.id).limit(1).maybeSingle();if(!m){setMsg('No encontramos tu negocio.');setLoading(false);return}const {data:c}=await supabase.from('companies').select('*').eq('id',m.company_id).maybeSingle();if(c){setCompany(c);setForm({business_name:c.business_name||'',legal_name:c.legal_name||'',tax_id:c.tax_id||'',address:c.address||'',phone:c.phone||'',email:c.email||'',currency:c.currency||'PEN',igv:c.igv??18});setLogo(c.logo_url||'')}setLoading(false)})()},[])
 const save=async e=>{e.preventDefault();setSaving(true);setMsg('');const {error}=await supabase.from('companies').update({...form,igv:Number(form.igv)}).eq('id',company?.id);setSaving(false);setMsg(error?error.message:'Configuración guardada correctamente.');if(!error)setCompany({...company,...form,igv:Number(form.igv)})}
 const uploadLogo=async()=>{if(!file||!company)return;setSaving(true);setMsg('');if(!file.type.startsWith('image/')){setSaving(false);return setMsg('Selecciona una imagen válida.')}if(file.size>2*1024*1024){setSaving(false);return setMsg('El logo no puede superar 2 MB.')}const ext=(file.name.split('.').pop()||'png').toLowerCase();const path=`${company.id}/logo.${ext}`;const {error}=await supabase.storage.from('company-logos').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(error){setSaving(false);return setMsg(error.message)}const {data}=supabase.storage.from('company-logos').getPublicUrl(path);const {error:updateError}=await supabase.from('companies').update({logo_url:data.publicUrl}).eq('id',company.id);setSaving(false);if(updateError)return setMsg(updateError.message);setLogo(data.publicUrl);setFile(null);setMsg('Logo actualizado correctamente.')}
 if(loading)return <main className="shell"><section className="main"><div className="card">Cargando configuración…</div></section></main>
 return <main className="shell"><header className="topbar"><a className="brand" href="/dashboard">Cotiza<span>Ya</span></a><a href="/dashboard">Inicio</a></header><section className="main"><form className="form" onSubmit={save}><p className="eyebrow">NEGOCIO</p><h1>Configuración</h1><p className="muted">Estos datos aparecerán automáticamente en tus cotizaciones.</p>{msg&&<div className="notice">{msg}</div>}<div className="field"><label>Nombre comercial</label><input required value={form.business_name} onChange={e=>setForm({...form,business_name:e.target.value})}/></div><div className="field"><label>Razón social</label><input value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})}/></div><div className="field"><label>RUC / documento fiscal</label><input value={form.tax_id} onChange={e=>setForm({...form,tax_id:e.target.value})}/></div><div className="field"><label>Dirección</label><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div><div className="grid two"><div className="field"><label>Teléfono</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="field"><label>Correo del negocio</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div></div><div className="grid two"><div className="field"><label>Moneda</label><select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option value="PEN">Soles (PEN)</option><option value="USD">Dólares (USD)</option></select></div><div className="field"><label>IGV (%)</label><input type="number" min="0" max="100" step="0.01" value={form.igv} onChange={e=>setForm({...form,igv:e.target.value})}/></div></div><button className="btn" disabled={saving}>{saving?'Guardando…':'Guardar configuración'}</button></form><div className="card" style={{maxWidth:620,margin:'16px auto'}}><h2>Logo del negocio</h2><p className="muted">PNG, JPG o WEBP · máximo 2 MB.</p>{logo&&<img src={logo} alt="Logo del negocio" style={{display:'block',maxWidth:220,maxHeight:120,objectFit:'contain',margin:'15px 0',border:'1px solid #e6eaf0',borderRadius:12,padding:10}}/>}<div className="field"><label>Seleccionar logo</label><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></div><button type="button" className="btn secondary" onClick={uploadLogo} disabled={!file||saving}>{saving?'Subiendo…':'Subir logo'}</button></div></section></main>
}
