'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase'
export default function Historial(){
 const [quotes,setQuotes]=useState([]),[payments,setPayments]=useState([]),[currency,setCurrency]=useState('PEN'),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[msg,setMsg]=useState('')
 const load=async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login';return}const {data:m}=await supabase.from('company_members').select('company_id').eq('user_id',user.id).limit(1).maybeSingle();if(!m){setMsg('No encontramos tu negocio.');setLoading(false);return}const [{data:q,error},{data:c},{data:p}]=await Promise.all([supabase.from('quotes').select('*, clients(name)').eq('company_id',m.company_id).order('created_at',{ascending:false}),supabase.from('companies').select('currency').eq('id',m.company_id).maybeSingle(),supabase.from('client_payments').select('quote_id,amount')]);if(error)setMsg(error.message);setQuotes(q||[]);setCurrency(c?.currency||'PEN');setPayments(p||[]);setLoading(false)};useEffect(()=>{load()},[])
 const paidByQuote=useMemo(()=>payments.reduce((a,p)=>{if(p.quote_id)a[p.quote_id]=(a[p.quote_id]||0)+Number(p.amount||0);return a},{}),[payments])
 const filtered=useMemo(()=>quotes.filter(q=>(!status||q.status===status)&&((q.quote_number||'').toLowerCase().includes(search.toLowerCase())||(q.clients?.name||'').toLowerCase().includes(search.toLowerCase()))),[quotes,search,status]);const remove=async id=>{if(!confirm('¿Eliminar esta cotización?'))return;const {error}=await supabase.from('quotes').delete().eq('id',id);if(error)setMsg(error.message);else load()};const label=s=>({draft:'Borrador',sent:'Enviada',accepted:'Aceptada',rejected:'Rechazada',expired:'Vencida'}[s]||s);const symbol=currency==='USD'?'$':'S/';const paymentLabel=(q)=>{const paid=paidByQuote[q.id]||0;if(paid>=Number(q.total||0)&&Number(q.total||0)>0)return 'Pagada';if(paid>0)return 'Pago parcial';return 'Pendiente'}
 if(loading)return <main className="shell"><section className="main"><div className="card">Cargando historial…</div></section></main>
 return <main className="shell"><header className="topbar"><a className="brand" href="/dashboard">Cotiza<span>Ya</span></a><a href="/dashboard">Inicio</a></header><section className="main"><div className="hero"><div><p className="eyebrow">OPERACIONES</p><h1>Historial</h1><p className="muted">Consulta todas tus cotizaciones guardadas.</p></div><a className="btn" href="/cotizacion">+ Nueva cotización</a></div><div className="card" style={{marginBottom:16}}><div className="grid two"><div className="field"><label>Buscar</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Número o cliente"/></div><div className="field"><label>Estado</label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option><option value="draft">Borrador</option><option value="sent">Enviada</option><option value="accepted">Aceptada</option><option value="rejected">Rechazada</option><option value="expired">Vencida</option></select></div></div></div>{msg&&<div className="notice">{msg}</div>}<div className="list">{filtered.length===0?<div className="card"><h3>No hay resultados</h3><p className="muted">Prueba otro filtro o crea una nueva cotización.</p></div>:filtered.map(q=>{const paid=paidByQuote[q.id]||0;const pending=Math.max(Number(q.total||0)-paid,0);return <div className="card" key={q.id}><div className="row"><div style={{flex:1}}><h3>{q.quote_number}</h3><p className="muted">{q.clients?.name||'Sin cliente'} · {q.issue_date} · {label(q.status)}</p><p className="muted">Pago: <b>{paymentLabel(q)}</b>{q.valid_until?' · Válida hasta: '+q.valid_until:''}</p></div><div style={{textAlign:'right'}}><strong>{symbol} {Number(q.total||0).toFixed(2)}</strong><div className="muted" style={{fontSize:12}}>Pagado {symbol} {paid.toFixed(2)} · Saldo {symbol} {pending.toFixed(2)}</div><div className="actions"><a className="btn secondary small" href={'/cotizacion/'+q.id}>Abrir</a><button className="btn danger small" onClick={()=>remove(q.id)}>Eliminar</button></div></div></div></div>})}</div></section></main>
}