'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'

export default function Dashboard(){
 const [user,setUser]=useState(null); const [company,setCompany]=useState(null); const [loading,setLoading]=useState(true)
 useEffect(()=>{let mounted=true;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href='/login';return}const {data:member}=await supabase.from('company_members').select('company_id,role').eq('user_id',user.id).limit(1).maybeSingle();if(member){const {data:c}=await supabase.from('companies').select('*').eq('id',member.company_id).maybeSingle();if(mounted)setCompany(c)}if(mounted){setUser(user);setLoading(false)}})();return()=>{mounted=false}},[])
 const logout=async()=>{await supabase.auth.signOut();window.location.href='/login'}
 if(loading)return <main className="shell"><section className="main"><div className="card"><h1>Cargando CotizaYa…</h1></div></section></main>
 return <main className="shell"><header className="topbar"><a className="brand" href="/dashboard">Cotiza<span>Ya</span></a><button className="btn secondary small" onClick={logout}>Salir</button></header><section className="main"><div className="hero"><div><p className="eyebrow">PANEL DE NEGOCIO</p><h1>{company?.business_name||'Mi negocio'}</h1><p className="muted">Bienvenido, {user?.user_metadata?.full_name||'usuario'}.</p></div><a className="btn" href="/cotizacion">+ Nueva cotización</a></div><div className="grid"><a className="card linkcard" href="/clientes"><strong>Clientes</strong><span>Gestiona clientes y sus expedientes.</span></a><a className="card linkcard" href="/productos"><strong>Productos y servicios</strong><span>Guarda precios para cotizar más rápido.</span></a><a className="card linkcard" href="/historial"><strong>Historial</strong><span>Consulta tus cotizaciones guardadas.</span></a><a className="card linkcard" href="/configuracion"><strong>Configuración del negocio</strong><span>Logo, datos comerciales, moneda e IGV.</span></a></div></section></main>
